services:
  app:
    image: node:19-alpine
    command: npm run start:dev
    ports:
      - 3002:3002
    working_dir: /backend-setup
    volumes:
      - ./:/backend-setup
    environment:
      NODE_ENV: development
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DATABASE: 'test1'

volumes:
  db:
